//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Project.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graduation_Project.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;
        ///                     Our website aims to provide several customized services to the user, whether the user is a patient or a doctor, as the
        ///                     site has several features and advantages, for example:
        ///                     &lt;br&gt; 
        ///                     the site allows to register an account of its own, in order to
        ///                     maintain security and provide features for the registered account. For example, there are four fixed services that
        ///                     Provided by the s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentAbout {
            get {
                return ResourceManager.GetString("ContentAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuberculosis (TB) is a bacterial infection spread through inhaling tiny droplets from the coughs or sneezes of
        ///                        an infected person. It mainly affects the lungs, but it can affect any part of the body, including the tummy
        ///                        (abdomen), glands, bones and nervous system..
        /// </summary>
        public static string ContentDisease_1 {
            get {
                return ResourceManager.GetString("ContentDisease_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pneumonia is swelling (inflammation) of the tissue in one or both lungs. It&apos;s usually caused by a bacterial 
        ///                        infection or a virus.
        ///                        The symptoms of pneumonia can develop suddenly over 24 to 48 hours, or they may come on more slowly 
        ///                        over several days. Pneumonia is usually the result of a bacterial infection..
        /// </summary>
        public static string ContentDisease_2 {
            get {
                return ResourceManager.GetString("ContentDisease_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung cancer is a type of cancer that begins in the lungs. Your lungs are two spongy organs in your chest that 
        ///                        take in oxygen when you inhale and release carbon dioxide when you exhale. Lung cancer is the leading cause 
        ///                        of cancer deaths worldwide..
        /// </summary>
        public static string ContentDisease_3 {
            get {
                return ResourceManager.GetString("ContentDisease_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coronaviruses are a type of virus. There are many different kinds, and some cause disease. A coronavirus 
        ///                        identified in 2019, SARS-CoV-2, has caused a pandemic of respiratory illness, called COVID-19. The coronavirus 
        ///                        can be spread from person to person..
        /// </summary>
        public static string ContentDisease_4 {
            get {
                return ResourceManager.GetString("ContentDisease_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asthma is a condition in which your airways narrow and swell and may produce extra mucus. This can make 
        ///                        breathing difficult and trigger coughing, a whistling sound (wheezing) when you breathe out and shortness of 
        ///                        breath..
        /// </summary>
        public static string ContentDisease_5 {
            get {
                return ResourceManager.GetString("ContentDisease_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic obstructive pulmonary disease is a leading cause of death and disability, but has only recently been 
        ///                        extensively explored from a cellular and molecular perspective. The inflammation and proteolysis in chronic 
        ///                        obstructive pulmonary disease is an amplification of the normal inflammatory response to cigarette smoke..
        /// </summary>
        public static string ContentDisease_6 {
            get {
                return ResourceManager.GetString("ContentDisease_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulmonary hypertension (PH) is high blood pressure in the lungs. This means that the blood vessels that carry 
        ///                        blood from the heart to the lungs become hard and narrow, making the heart work harder to pump the blood 
        ///                        through..
        /// </summary>
        public static string ContentDisease_7 {
            get {
                return ResourceManager.GetString("ContentDisease_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pulmonary embolism is a blood clot that blocks and stops blood flow to an artery in the lung. In most cases, 
        ///                        the blood clot starts in a deep vein in the leg and travels to the lung. Rarely, the clot forms in a vein in another 
        ///                        part of the body. When a blood clot forms in one or more of the deep veins in the body, it&apos;s called a deep vein 
        ///                        thrombosis (DVT)..
        /// </summary>
        public static string ContentDisease_8 {
            get {
                return ResourceManager.GetString("ContentDisease_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The medical advice blog aims to increase awareness among patients, increase the effectiveness of
        ///                    communication between patients and doctors, and facilitate knowledge of the risks of diseases, as well as the
        ///                    medical reasons that avoid these diseases..
        /// </summary>
        public static string ContentService_1 {
            get {
                return ResourceManager.GetString("ContentService_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disease detection process is useful for discovering a group of serious diseases that affect human health and that may lead to death if they are not resisted, such as pneumonia, tuberculosis and lung cancer..
        /// </summary>
        public static string ContentService_2 {
            get {
                return ResourceManager.GetString("ContentService_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box aims to measure the temperature, heartbeat and blood oxygen level to a large extent Accurate proportion, this is intended to show the initial indications of the patient&apos;s condition, as if an abnormality had occurred In any of them, it is seen that certain symptoms of the respiratory tract and breathing appear..
        /// </summary>
        public static string ContentService_3 {
            get {
                return ResourceManager.GetString("ContentService_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung transplantation in the system helps patients with serious diseases such as pulmonary fibrosis to all types of lung cancer and other diseases, to facilitate delivery to hospitals where the organ is available for Completing the transplant and saving the patient&apos;s life, but this is through several proofs..
        /// </summary>
        public static string ContentService_4 {
            get {
                return ResourceManager.GetString("ContentService_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patient Safety Initiative aims to increase the process of awareness among the community in order to
        ///                    maintain public safety for all, especially from lung syndrome diseases related to the breathing process, and to
        ///                    find appropriate solutions through programs and blogs that allow this,
        ///                    &lt;br&gt;
        ///                    whether in order to facilitate
        ///                    knowledge of the disease itself or finding treatment and solutions that Help with th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentSlider_1 {
            get {
                return ResourceManager.GetString("ContentSlider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our system aims to allow the process of communication between the patient and the doctor, in order to
        ///                    facilitate the recovery process for the patient and for the sake of awareness and general knowledge,
        ///                    &lt;br&gt;
        ///                    through medical advice that takes place in the system and allows the patient to inquire about the medical and the
        ///                    doctor can help and respond to it..
        /// </summary>
        public static string ContentSlider_2 {
            get {
                return ResourceManager.GetString("ContentSlider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You probably already know that smoking increases your risk of lung cancer. But this is not the only disease
        ///                    that can cause it. In fact, smoking is associated with most lung diseases, including chronic obstructive
        ///                    pulmonary disease, idiopathic pulmonary fibrosis, and asthma.
        ///                    &lt;br&gt;
        ///                    It also makes smokers more likely to die.
        ///                    Smoking also causes lungs to age more rapidly. Eventually, the chemicals can change l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentSlider_3 {
            get {
                return ResourceManager.GetString("ContentSlider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases.
        /// </summary>
        public static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERT DOCTORS.
        /// </summary>
        public static string ExpertDoctors {
            get {
                return ResourceManager.GetString("ExpertDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPY PATIENTS.
        /// </summary>
        public static string HappyPatients {
            get {
                return ResourceManager.GetString("HappyPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Medical Advices.
        /// </summary>
        public static string LatestMedicalAdvices {
            get {
                return ResourceManager.GetString("LatestMedicalAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Advices.
        /// </summary>
        public static string MedicalAdvices {
            get {
                return ResourceManager.GetString("MedicalAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVED LUNGS.
        /// </summary>
        public static string SavedLungs {
            get {
                return ResourceManager.GetString("SavedLungs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Common Diseases.
        /// </summary>
        public static string SomeCommonDiseases {
            get {
                return ResourceManager.GetString("SomeCommonDiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string SubTitleAbout {
            get {
                return ResourceManager.GetString("SubTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passion for caring.
        /// </summary>
        public static string SubTitleSlider_1 {
            get {
                return ResourceManager.GetString("SubTitleSlider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Experience In Bulding.
        /// </summary>
        public static string SubTitleSlider_2 {
            get {
                return ResourceManager.GetString("SubTitleSlider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to higher level of care.
        /// </summary>
        public static string SubTitleSlider_3 {
            get {
                return ResourceManager.GetString("SubTitleSlider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Hands With GOBA Team.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuberculosis.
        /// </summary>
        public static string TitleDisease_1 {
            get {
                return ResourceManager.GetString("TitleDisease_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pneumonia.
        /// </summary>
        public static string TitleDisease_2 {
            get {
                return ResourceManager.GetString("TitleDisease_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung Cancer.
        /// </summary>
        public static string TitleDisease_3 {
            get {
                return ResourceManager.GetString("TitleDisease_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID.
        /// </summary>
        public static string TitleDisease_4 {
            get {
                return ResourceManager.GetString("TitleDisease_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asthma.
        /// </summary>
        public static string TitleDisease_5 {
            get {
                return ResourceManager.GetString("TitleDisease_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic obstructive pulmonary disease.
        /// </summary>
        public static string TitleDisease_6 {
            get {
                return ResourceManager.GetString("TitleDisease_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulmonary Hypertension.
        /// </summary>
        public static string TitleDisease_7 {
            get {
                return ResourceManager.GetString("TitleDisease_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked lung artery.
        /// </summary>
        public static string TitleDisease_8 {
            get {
                return ResourceManager.GetString("TitleDisease_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Advices.
        /// </summary>
        public static string TitleService_1 {
            get {
                return ResourceManager.GetString("TitleService_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases Detection.
        /// </summary>
        public static string TitleService_2 {
            get {
                return ResourceManager.GetString("TitleService_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Box.
        /// </summary>
        public static string TitleService_3 {
            get {
                return ResourceManager.GetString("TitleService_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung Transplant.
        /// </summary>
        public static string TitleService_4 {
            get {
                return ResourceManager.GetString("TitleService_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Safety &lt;br&gt; Initiatives.
        /// </summary>
        public static string TitleSlider_1 {
            get {
                return ResourceManager.GetString("TitleSlider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication between
        ///                    &lt;br&gt;
        ///                    patients and Doctors.
        /// </summary>
        public static string TitleSlider_2 {
            get {
                return ResourceManager.GetString("TitleSlider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung cancer
        ///                    &lt;br&gt;
        ///                    and deadly smoking.
        /// </summary>
        public static string TitleSlider_3 {
            get {
                return ResourceManager.GetString("TitleSlider_3", resourceCulture);
            }
        }
    }
}
